version: "3.9"
services:
    db:
        image: postgres:15
        container_name: prisma_postgres
        restart: always
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: prisma_db
        volumes:
            - prisma_postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: prisma_app
        restart: always
        environment:
            DATABASE_URL: postgres://prisma:prisma@db:5432/prisma_db
        depends_on:
            - db
        ports:
            - "3000:3000"
        command: ["sh", "-c", "npx prisma migrate deploy && npm start"]

volumes:
    prisma_postgres_data:
