version: "3.8"

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: cbn
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432" # Expose port 5432

volumes:
    postgres_data:
