openapi: 3.0.0
info:
  title: Transaction API
  description: API for retrieving transaction details.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /transaction/{transactionId}:
    get:
      tags:
        - Transaction
      summary: Get transaction details
      description: Retrieve details of a specific transaction by transaction ID.
      parameters:
        - name: transactionId
          in: path
          required: true
          description: The ID of the transaction to retrieve.
          schema:
            type: string
      responses:
        "200":
          description: Successful response with transaction details
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    description: The unique identifier of the transaction.
                  transactionDate:
                    type: string
                    format: date-time
                    description: The date when the transaction occurred.
                  transactionPlage:
                    type: string
                    description: Additional information about the transaction.
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
  /cashlimit/{posID}:
    get:
      tags:
        - CashLimit
      summary: Get cash limit for a pos
      description: Pos limit is 500,000 per week per customer
      parameters:
        - name: posID
          in: path
          required: true
          description: BVN of the pos
          schema:
            type: string
      responses:
        "200":
          description: Successful response with transaction details
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    description: The unique identifier of the transaction.
                  transactionDate:
                    type: string
                    format: date-time
                    description: The date when the transaction occurred.
                  transactionPlage:
                    type: string
                    description: Additional information about the transaction.
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
  /cashlimit/{agentId}:
    get:
      tags:
        - CashLimit
      summary: Agent banking terminals
      description: Limit of transaction cashout is 100,000 per day per customer
      parameters:
        - name: agentId
          in: path
          required: true
          description: ID of the Agent
          schema:
            type: string
      responses:
        "200":
          description: Successful response with transaction details
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    description: The unique identifier of the transaction.
                  transactionDate:
                    type: string
                    format: date-time
                    description: The date when the transaction occurred.
                  transactionPlage:
                    type: string
                    description: Additional information about the transaction.
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
  /cashlimit/{agentId1}:
    get:
      tags:
        - CashLimit
      summary: Get cumulative cash limit for a transaction
      description: Retrieve details of a specific transaction by transaction ID.
      parameters:
        - name: agentId1
          in: path
          required: true
          description: Id of the agent
          schema:
            type: string
      responses:
        "200":
          description: Successful response with transaction details
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    description: The unique identifier of the transaction.
                  transactionDate:
                    type: string
                    format: date-time
                    description: The date when the transaction occurred.
                  transactionPlage:
                    type: string
                    description: Additional information about the transaction.
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
  /compliance/{merchantId}:
    get:
      tags:
        - Compliance
      summary: Get cash limit for a transaction
      description: Retrieve details of a specific transaction by transaction ID.
      parameters:
        - name: merchantId
          in: path
          required: true
          description: Id of the merchant
          schema:
            type: string
      responses:
        "200":
          description: Successful response with transaction details
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    description: The unique identifier of the transaction.
                  transactionDate:
                    type: string
                    format: date-time
                    description: The date when the transaction occurred.
                  transactionPlage:
                    type: string
                    description: Additional information about the transaction.
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
  /compliance/{agentId}:
    get:
      tags:
        - Compliance
      summary: Get cash limit for a transaction
      description: Retrieve details of a specific transaction by transaction ID.
      parameters:
        - name: agentId
          in: path
          required: true
          description: Id of the agent
          schema:
            type: string
      responses:
        "200":
          description: Successful response with transaction details
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    description: The unique identifier of the transaction.
                  transactionDate:
                    type: string
                    format: date-time
                    description: The date when the transaction occurred.
                  transactionPlage:
                    type: string
                    description: Additional information about the transaction.
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
  /topcashincashout/{merchantId}:
    get:
      tags:
        - Top Cash in Cash Out
      summary: Get cash limit for a transaction
      description: Retrieve details of a specific transaction by transaction ID.
      parameters:
        - name: merchantId
          in: path
          required: true
          description: Id of the merchant
          schema:
            type: string
      responses:
        "200":
          description: Successful response with transaction details
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    description: The unique identifier of the transaction.
                  transactionDate:
                    type: string
                    format: date-time
                    description: The date when the transaction occurred.
                  transactionPlage:
                    type: string
                    description: Additional information about the transaction.
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
  /topcashincashout/{agentId}:
    get:
      tags:
        - Top Cash in Cash Out
      summary: Get cash limit for a transaction
      description: Retrieve details of a specific transaction by transaction ID.
      parameters:
        - name: agentId
          in: path
          required: true
          description: Id of the agent
          schema:
            type: string
      responses:
        "200":
          description: Successful response with transaction details
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                    description: The unique identifier of the transaction.
                  transactionDate:
                    type: string
                    format: date-time
                    description: The date when the transaction occurred.
                  transactionPlage:
                    type: string
                    description: Additional information about the transaction.
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
